# Generated by Django 3.0.11 on 2021-01-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daten',
            options={'managed': False},
        ),
    ]
